# Generated by Django 4.2 on 2024-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The name of the genre.", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the movie.", max_length=255
                    ),
                ),
                (
                    "poster",
                    models.URLField(
                        help_text="URL to the movie's poster.", max_length=255
                    ),
                ),
                (
                    "year_release",
                    models.IntegerField(help_text="The year the movie was released."),
                ),
                (
                    "metacritic_rating",
                    models.IntegerField(help_text="Metacritic rating of the movie."),
                ),
                (
                    "runtime",
                    models.IntegerField(
                        help_text="The duration of the movie in minutes."
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Genres of the movie.",
                        related_name="movies",
                        to="core.genre",
                    ),
                ),
            ],
        ),
    ]
