# Generated by Django 4.2 on 2024-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_movie_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="vote_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
